/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef HEAVISIDE
#define HEAVISIDE

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooConstVar.h"
 
class Heaviside : public RooAbsReal {
public:
  Heaviside() {} ; 
  Heaviside(const char *name, const char *title,
	    RooAbsReal& _x,
	    RooAbsReal& _f,
	    RooAbsReal& _x0 = RooFit::RooConst(0.0)
           );
  Heaviside(const Heaviside& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Heaviside(*this,newname); }
  inline virtual ~Heaviside() { }

protected:

  RooRealProxy x ;
  RooRealProxy f ;
  RooRealProxy x0 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(Heaviside,1) // Your description goes here...
};
 
#endif
